$('#link-ventana').click(function(){
    $('.card-body').load('../src/ventana.html');
    $('#link-ventana').addClass('active');
    $('#link-temperatura').removeClass('active');
    $('#link-puerta').removeClass('active');
});
$('#link-temperatura').click(function(){
    $('.card-body').load('../src/temperatura.html');
    $('#link-temperatura').addClass('active');
    $('#link-ventana').removeClass('active');
    $('#link-puerta').removeClass('active');
});
$('#link-puerta').click(function(){
    $('.card-body').load('../src/puerta.html');
    $('#link-puerta').addClass('active');
    $('#link-temperatura').removeClass('active');
    $('#link-ventana').removeClass('active');
});